language: rust
addons:
  apt:
    update: yes
    packages:
      - libgtk-3-dev
      - libgio-cil
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
